GENRES = {}
# 9 GENRES USED FOR CLASSIFICATION
GENRES['core'] = [ 'blues',
                   'classical',
                   'country',
                   'electronic',
                   'hiphop',
                   'jazz',
                   'metal',
                   'reggae',
                   'rock' ]

GENRES['mood'] = [ 'angry',
                   'chill',
                   'energized',
                   'funny',
                   'happy',
                   'inspired',
                   'loved',
                   'sad',
                   'tense' ]

GENRES['vocals'] = [ 'male',
                     'female' ]

GENRES['blues'] = [ 'rhythm-and-blues',
                    'country-blues',
                    'chicago-blues',
                    'delta-blues',
                    'blues-rock',
                    'classic-female-blues',
                    'jump-blues',
                    'electric-blues',
                    'ragtime',
                    'boogie-woogie',
                    'texas-blues',
                    'british-blues',
                    'memphis-blues',
                    'west-coast-blues',
                    'new-orleans-blues',
                    'swing-music',
                    'swamp-blues',
                    'jazz-blues',
                    'dixieland',
                    'soul-blues',
                    'gospel-blues' ]

GENRES['classical'] = [ 'symphony',
                        'opera',
                        'baroque-music',
                        'oratorio',
                        'concerto',
                        'medieval-music',
                        'sonata',
                        'chamber-music',
                        'renaissance-music',
                        'opera-seria',
                        'overture',
                        'nocturne',
                        'ballet' ]


GENRES['electronic'] = [ 'techno',
                         'house',
                         'dubstep',
                         'trance',
                         'drum-and-bass',
                         'edm',
                         'ambient',
                         'breakbeat',
                         'trap',
                         'progressive-house',
                         'tech-house',
                         'disco',
                         'synth-pop',
                         'hardstyle',
                         'downtempo',
                         'acid-house',
                         'jungle',
                         'electro-house',
                         'idm',
                         'deep-house',
                         'future-bass',
                         'dubstep',
                         'electro' ]

GENRES['reggae'] = [ 'calypso',
                     'dancehall',
                     'dembow',
                     'dub',
                     'dub-poetry',
                     'early-reggae',
                     'jamaica-ska',
                     'jungle',
                     'lovers-rock',
                     'mento',
                     'moombahton',
                     'music-of-jamaica',
                     'ragga',
                     'reggae-en-espanol',
                     'reggae-fusion',
                     'reggae-rock',
                     'reggaestep',
                     'reggaeton',
                     'rocksteady',
                     'roots-reggae',
                     'ska',
                     'toasting',
                     'two-tone',
                     'zouk' ]

GENRES['hiphop'] = [ 'alternative-hip-hop',
                     'boom-bap',
                     'chopped-and-screwed',
                     'cloud-rap',
                     'conscious-hip-hop',
                     'country-rap',
                     'crunk',
                     'drill',
                     'emo-rap',
                     'g-funk',
                     'gangsta-rap',
                     'grime',
                     'hardcore',
                     'horrorcore',
                     'jazz-rap',
                     'latin-trap',
                     'lo-fi',
                     'old-school',
                     'pop-rap',
                     'rap-rock',
                     'southern-hip-hop' ]

GENRES['jazz'] = [ 'bebop',
                   'jazz-fusion',
                   'free-jazz',
                   'cool-jazz',
                   'dixieland',
                   'swing',
                   'ragtime',
                   'blues',
                   'hard-bop',
                   'latin-jazz',
                   'smooth-jazz',
                   'modal-jazz',
                   'acid-jazz',
                   'avant-garde-jazz',
                   'soul-jazz',
                   'post-jazz',
                   'big-band',
                   'third-stream',
                   'gypsy-jazz',
                   'afro-cuban-jazz',
                   'stride',
                   'jazz-funk' ]

GENRES['country'] = [ 'bluegrass',
                      'country-rock',
                      'outlaw-country',
                      'country-pop',
                      'honky-tonk',
                      'western-swing',
                      'alternative-country',
                      'nashville-sound',
                      'americana',
                      'red-dirt',
                      'western-music',
                      'cowpunk',
                      'neotraditional-country',
                      'appalachian-music',
                      'bro-country',
                      'texas-country',
                      'roots-rock',
                      'progressive-country',
                      'truck-driving-country' ]

GENRES['metal'] = [ 'alternative-metal',
                    'avant-garde-metal',
                    'black-metal',
                    'crossover-thrash',
                    'crust-punk',
                    'death-metal',
                    'deathcore',
                    'doom-metal',
                    'funk-metal',
                    'glam-metal',
                    'goregrind',
                    'gothic-metal',
                    'grindcore',
                    'groove-metal',
                    'heavy-metal',
                    'industrial-metal',
                    'melodic-death-metal',
                    'metalcore',
                    'neoclassical-metal',
                    'post-metal',
                    'power-metal',
                    'progressive-metal',
                    'speed-metal',
                    'symphonic-metal' ]

GENRES['rock'] = [ 'blues-rock',
                   'country-rock',
                   'heavy-metal',
                   'indie-rock',
                   'acoustic-rock',
                   'punk-rock',
                   'psychedelic',
                   'hard-rock',
                   'grunge',
                   'folk',
                   'progressive-rock',
                   'funk',
                   'art-rock',
                   'new-wave',
                   'rockabilly',
                   'garage-rock',
                   'rock-and-roll',
                   'alternative',
                   'soft-rock',
                   'post-rock',
                   'post-punk',
                   'gothic-rock',
                   'pop-rock' ]

# DEFINE PATHS
DATAPATH        =   '/home/ubuntu/choppedfile/train'
RAW_DATAPATH    =   '/home/ubuntu/genre-classifier/utils/raw_data.pkl'
SET_DATAPATH    =   '/home/ubuntu/genre-classifier/utils/set.pkl'
MODELPATH       =   '/home/ubuntu/genre-classifier/model/net.pt'
