# 9 GENRES USED FOR CLASSIFICATION
GENRES['core'] = [ 'blues',
                   'classical',
                   'country',
                   'electronic',
                   'hiphop',
                   'jazz',
                   'metal',
                   'reggae',
                   'rock' ]

GENRES['blues'] = [ 'blues-rock',
                    'delta-blues',
                    'louisiana-blues',
                    'rock-and-roll',
                    'boogie-woogie',
                    'dixieland',
                    'memphis-blues',
                    'soul-blues',
                    'british-blues',
                    'electric-blues',
                    'new-orleans-blues',
                    'swamp-blues',
                    'chicago-blues',
                    'gospel-blues',
                    'piedmont-blues',
                    'swing-music',
                    'classic-female-blues',
                    'jazz-blues',
                    'ragtime',
                    'texas-blues',
                    'country-blues',
                    'jump-blues',
                    'rhythm-and-blues',
                    'west-coast-blues' ]

GENRES['classical'] = [ 'ballad',
                        'ballet',
                        'baroque-music',
                        'chamber-music',
                        'concerto',
                        'divertimento',
                        'early-music',
                        'impressionism-music',
                        'medieval-music',
                        'minimal-music',
                        'modernism',
                        'motet',
                        'nocturne',
                        'opera-seria',
                        'opera',
                        'operetta',
                        'oratorio',
                        'overture',
                        'renaissance-music',
                        'romantic-music',
                        'scherzo',
                        'singspiel',
                        'sonata',
                        'symphony' ]


GENRES['electronic'] = [ 'acid-house',
                         'ambient',
                         'breakbeat',
                         'deep-house',
                         'disco',
                         'downtempo',
                         'drum-and-bass',
                         'dubstep',
                         'edm',
                         'electro',
                         'electro-house',
                         'future-bass',
                         'garage',
                         'hardstyle',
                         'hip-hop',
                         'house',
                         'idm',
                         'jungle',
                         'progressive-house',
                         'synth-pop',
                         'tech-house',
                         'techno',
                         'trance',
                         'trap' ]

GENRES['reggae'] = [ 'calypso',
                     'dancehall',
                     'dembow',
                     'dub',
                     'dub-poetry',
                     'early-reggae',
                     'jamaica-ska',
                     'jungle',
                     'lovers-rock',
                     'mento',
                     'moombahton',
                     'music-of-jamaica',
                     'ragga',
                     'reggae-en-espano',
                     'reggae-fusion',
                     'reggae-rock',
                     'reggaestep',
                     'reggaeton',
                     'rocksteady',
                     'roots-reggae',
                     'ska',
                     'toasting',
                     'two-tone',
                     'zouk' ]

GENRES['hiphop'] = [ 'alternative-hip-hop',
                     'boom-bap',
                     'chopped-and-screwed',
                     'cloud-rap',
                     'comedy-hip-hop',
                     'conscious-hip-hop',
                     'country-rap',
                     'crunk',
                     'drill',
                     'east-coast',
                     'emo-rap',
                     'g-funk',
                     'gangsta-rap',
                     'grime',
                     'hardcore',
                     'horrorcore',
                     'hyphy',
                     'jazz-rap',
                     'latin-trap',
                     'old-school',
                     'pop-rap',
                     'rap-rock',
                     'southern-hip-hop',
                     'trap-music' ]

GENRES['jazz'] = [ 'acid-jazz',
                   'afro-cuban-jazz',
                   'avant-garde-jazz',
                   'bebop',
                   'big-band',
                   'blues',
                   'cool-jazz',
                   'dixieland',
                   'free-jazz',
                   'gypsy-jazz',
                   'hard-bop',
                   'jazz-funk',
                   'jazz-fusion',
                   'latin-jazz',
                   'modal-jazz',
                   'post-bop',
                   'ragtime',
                   'rnb',
                   'smooth-jazz',
                   'soul-jazz',
                   'soul-music',
                   'stride',
                   'swing',
                   'third-stream' ]

GENRES['country'] = [ 'alternative-country',
                      'americana',
                      'appalachian-music',
                      'bakersfield-sound',
                      'bluegrass',
                      'bro-country',
                      'country-pop',
                      'country-rap',
                      'country-rock',
                      'cowpunk',
                      'honky-tonk',
                      'nashville-sound',
                      'neotraditional-country',
                      'outlaw-country',
                      'progressive-country',
                      'punk-rock',
                      'red-dirt',
                      'rockabilly',
                      'roots-rock',
                      'texas-country',
                      'the-countrypolitan',
                      'truck-driving-country',
                      'western-music',
                      'western-swing' ]

GENRES['metal'] = [ 'alternative-metal',
                    'avant-garde-metal',
                    'black-metal',
                    'crossover-thrash',
                    'crust-punk',
                    'death-metal',
                    'deathcore',
                    'doom-metal',
                    'funk-metal',
                    'glam-metal',
                    'goregrind',
                    'gothic-metal',
                    'grindcore',
                    'groove-metal',
                    'heavy-metal',
                    'industrial-metal',
                    'melodic-death-metal',
                    'metalcore',
                    'neoclassical-metal',
                    'post-metal',
                    'power-metal',
                    'progressive-metal',
                    'speed-metal',
                    'symphonic-metal' ]

GENRES['rock'] = [ 'alternative-dance',
                   'alternative',
                   'art-rock',
                   'blues-rock',
                   'folk-rock',
                   'garage-rock',
                   'glam-rock',
                   'gothic-rock',
                   'grunge',
                   'hard-rock',
                   'heavy-metal',
                   'indie-rock',
                   'jazz-fusion',
                   'new-wave',
                   'pop-rock',
                   'post-punk',
                   'post-rock',
                   'progressive-rock',
                   'psychedelic-rock',
                   'punk-rock',
                   'rock-and-roll',
                   'rockabilly',
                   'soft-rock',
                   'surf-music' ]

# DEFINE PATHS
DATAPATH        =   '/tmp/choppedfile/jake'
RAW_DATAPATH    =   '../utils/raw_data.pkl'
SET_DATAPATH    =   '../utils/set.pkl'
MODELPATH       =   '../model/net.pt'
